WEBSITE-master/Api/urls.py
from django.conf.urls import include, url
from .views import *
from . import views

app_name = 'Api'

urlpatterns = [
		url(r'^login/$', Login.as_view(), name='login'),
		url(r'^courses/(?P<type>[\w\-]+)/(?P<menu>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CourseList.as_view(), name='course-list'),
        url(r'^doubts/(?P<course_id>\d+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', DoubtCreate.as_view(), name='doubt'),
		url(r'^courses/(?P<course_id>\d+)/doubts/$', CourseDoubt.as_view(), name='course-doubt'),
		url(r'^comments/(?P<doubt_id>\d+)/$', CommentCreate.as_view(), name='comment'),
		url(r'^quiz-details/(?P<quiz_id>[\w\-]+)/$', QuizDetails.as_view(), name='quiz-details'),
		url(r'^check-quiz/(?P<quiz_id>[\w\-]+)/(?P<course_id>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CheckQuiz.as_view(), name='check-quiz'),
		url(r'^comment-on-doubt/$', CommentOnDoubt.as_view(), name='comment-on-doubt'),
		url(r'^quiz-complete/$', QuizComplete.as_view(), name='quiz-complete'),
		url(r'^meeting/(?P<type>[\w\-]+)/$',MeetingManage.as_view(), name='meeting-create'),
		url(r'^all-student-quizes/(?P<course_id>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',AllStudentQuiz.as_view(), name='all-student-quizes'),
		url(r'^create-meeting/(?P<course_id>\d+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CreateMeeting.as_view(), name='create-meeting'),	
		
		url(r'^calling-stored-procedure/$', views.CallingStoredProcedure, name='calling-stored-procedure'),	
		
		# url(r'^test/$', views.Test, name='test'),
	]

WEBSITE-master/UserAuth/urls.py
from django.conf.urls import include, url
from . import views
from . import utils
from django.contrib.auth import logout

app_name = 'UserAuth'

urlpatterns = [
		url(r'^$', views.landingPage.as_view(), name='landingPage'),
		url(r'^login/$', views.Login.as_view(), name='login'),
		url(r'^signup/$', views.SignUp.as_view(), name='signup'),
		url(r'^signup-user/(?P<type>[\w\-]+)$', views.signupUser.as_view(), name='signup-user'),
		url(r'^login-user/(?P<type>[\w\-]+)', views.LoginUser.as_view(), name='login-user'),
		url(r'^send-verification-data/(?P<user_group>[\w\-]+)/(?P<send_to>[\w\-]+)$', views.send_verification_data, name='send-verification-data'),

		url(r'^show-message/$', utils.show_message, name='show-message'),

		url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
		url(r'^auth/callback/(?P<user_token>.+)$', views.redirectPage, name='redirection'),
	]

# Our Client Id and Client Key
# "_id": "5bd09a7e89128700158c1e94",
#     "email": "anurag.g16@iiits.in",
#     "group": "B01",
#     "callback": "localhost:8000/auth/callback/",
#     "__v": 0,
#     "clientSecret": "27da906cca2278407c4717551f8ccae5d2fb89da47009050f3671245f2a14440f9c282152877f7d6b08d3f19696d94844b9f74ac901752424045f9190910d0bd"

WEBSITE-master/gurukool_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('UserAuth.urls', namespace='UserAuth')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^professor/', include('Professor.urls', namespace="Professor")),
	url(r'^student/', include('Student.urls', namespace="Student")),
    url(r'^api/', include('Api.urls', namespace="Api")),
    url(r'^doubt/', include('Doubt.urls', namespace="Doubt")),
    url(r'^meeting/', include('Meeting.urls', namespace="Meeting")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WEBSITE-master/UserAuth/models.py
from django.db import models
from django.contrib.auth.models import User

class GenderChoice(models.Model):
	name = models.CharField(max_length=100, null=False, blank=False, unique=True)
	def __str__(self):
		return str(self.name)

class AuthID(models.Model):
	client_id = models.CharField(max_length=200)
	clientSecret = models.CharField(max_length=200)
	def __str__(self):
		return self.client_id + " " + self.clientSecret

# class Token(models.Model):
# 	username = models.CharField(max_length=100)
# 	token = models.CharField(max_length=200)
# 	def __str__(self):
# 		return self.username + " " + self.token

class InstituteProfile(models.Model):
	institute_id = models.CharField(unique=True, null=False, blank=False, max_length=100)
	name = models.CharField(max_length=200)
	address_city = models.CharField(max_length=200)
	address_district = models.CharField(max_length=200)
	address_state = models.CharField(max_length=200)
	address_country = models.CharField(max_length=200)
	address_pincode = models.IntegerField(null=True, blank=True)
	email_address = models.CharField(max_length=100, null=False, blank=False)
	phone_no = models.CharField(max_length=100, null=False, blank=False)
	website = models.CharField(max_length=100, null=False, blank=False)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.institute_id) + ' --> ' + str(self.name)

class ProfessorAuthProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	mobile_no = models.CharField(max_length=1000,blank=True, null=True)
	gender = models.ForeignKey(GenderChoice, on_delete=models.SET_NULL, null=True, blank=True)
	date_of_birth = models.DateField(blank=False, null=False)
	email_address = models.CharField(max_length=100, null=False, blank=False)

	email_verification_link = models.CharField(max_length=100, null=True, blank=True)
	email_verification_link_sent = models.BooleanField(default=False)
	email_verified = models.BooleanField(default=False)
	otp = models.IntegerField(default=0)
	otp_sent_to_mobile_no = models.BooleanField(default=False)
	otp_verified = models.BooleanField(default=False)

	def __str__(self):
		return str(self.user.username) + ' --> ' + str(self.user.id)

class StudentAuthProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	mobile_no = models.CharField(max_length=1000,blank=True, null=True)
	gender = models.ForeignKey(GenderChoice, on_delete=models.SET_NULL, null=True, blank=True)
	date_of_birth = models.DateField(blank=False, null=False)
	email_address = models.CharField(max_length=100, null=False, blank=False)

	email_verification_link = models.CharField(max_length=100, null=True, blank=True)
	email_verification_link_sent = models.BooleanField(default=False)
	email_verified = models.BooleanField(default=False)
	otp = models.IntegerField(default=0)
	otp_sent_to_mobile_no = models.BooleanField(default=False)
	otp_verified = models.BooleanField(default=False)

	def __str__(self):
		return str(self.user.username) + ' --> ' + str(self.user.id)

WEBSITE-master/UserAuth/views.py
import string
import re
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import *
from communications import *
from django.core import mail
from random import *
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login
from Student.models import *
from Professor.models import *
from django.contrib import messages
from django.views import View
from .utils import *
from django.contrib.auth.decorators import login_required
from django.conf import settings
import requests
# import simplejson as json
import json

SHOW_MESSAGE_URL = 'UserAuth:show-message'
EMAIL_VERIFICATION_LINK_LENGTH = 50
LOGIN_URL = 'UserAuth:landingPage'

def redirectPage(request, user_token):
	'''
		Redirects the page
		Takes input request method and user_token
		returns http response
	'''
	request.session['token'] = user_token
	payload = {"secret":"27da906cca2278407c4717551f8ccae5d2fb89da47009050f3671245f2a14440f9c282152877f7d6b08d3f19696d94844b9f74ac901752424045f9190910d0bd", "token":user_token}
	print(user_token)

	r=requests.post('https://serene-wildwood-35121.herokuapp.com/oauth/getDetails/', data=payload)
# json.dumps(response_data), content_type="application/json"
	# print("R = ", r.json())
	return HttpResponse(json.dumps(r.json()), content_type="application/json")
	# return HttpResponseRedirect(reverse('Student:dashboard'))

class landingPage(View):
	'''
	get Landing Page
	'''
	get_login_page = 'UserAuth/landingPage.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			if request.user.groups.filter(name='Professor').exists():
				return HttpResponseRedirect(reverse('Professor:dashboard'))
			elif request.user.groups.filter(name='Student').exists():
				return HttpResponseRedirect(reverse('Student:dashboard'))
		return render(request, self.get_login_page)

class Login(View):
	get_login_template = 'UserAuth/loginPage.html'
	# get_login_template = 'UserAuth/login.html'
	# get_login_template = 'UserAuth/signupPage.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			if request.user.groups.filter(name='Professor').exists():
				return HttpResponseRedirect(reverse('Professor:dashboard'))
			elif request.user.groups.filter(name='Student').exists():
				return HttpResponseRedirect(reverse('Student:dashboard'))
		gender_choices = GenderChoice.objects.all()
		return render(request, self.get_login_template, {"gender_choices": gender_choices})

	def post(self, request, *args, **kwargs):
		messages.error(request, 'BAD REQUEST')
		return HttpResponseRedirect(reverse(settings.MESSAGE_URL))

class LoginUser(View):
	def post(self, request, *args, **kwargs):
		try:
			type_of_user = kwargs.get('type', None)
			if type_of_user == 'professor':
				username = request.POST.get('professor_login_username')
				password = request.POST.get('professor_login_password')

				if username.isdigit():
					try:
						instance = ProfessorAuthProfile.objects.filter(mobile_no=username)
						if len(instance) > 1:
							message = 'More than one account is registered with this mobile number.  Kindly use Email-ID to login.'
							messages.warning(request, message)
							return HttpResponseRedirect(reverse('UserAuth:login'))
						else:
							instance = instance[0]
						username = instance.user.username
						user = authenticate(username=username, password=password)
						if user is not None:
							login(request, user)
							return HttpResponseRedirect(reverse('Professor:dashboard'))
						messages.warning(request, "Phone No and password doesn't match with any GURUKOOL PROFESSOR account.")
						return HttpResponseRedirect(reverse('UserAuth:login'))
					except:
						messages.warning(request, "No GURUKOOL PROFESSOR account is registered with that mobile no.")
						return HttpResponseRedirect(reverse('UserAuth:login'))
				else:
					try:
						match = re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', username)
						if match is None:
							messages.warning(request, 'E-mail entered is not a valid email-address')
							return HttpResponseRedirect(reverse('UserAuth:login'))
						try:
							instance = ProfessorAuthProfile.objects.get(email_address=username)
						except:
							messages.warning(request, 'No GURUKOOL PROFESSOR account registered with this email-address.')
							return HttpResponseRedirect(reverse('UserAuth:login'))
						user = authenticate(username=username, password=password)
						if user is not None:
							login(request, user)
							return HttpResponseRedirect(reverse('Professor:dashboard'))
						messages.warning(request, "Email address and Password does not match to any GURUKOOL PROFESSOR Account.")
						return HttpResponseRedirect(reverse('UserAuth:login'))
					except:
						messages.error(request, 'BAD REQUEST')
						return HttpResponseRedirect(reverse(settings.MESSAGE_URL))
			elif type_of_user == 'student':
				if request.method == 'POST':
					username = request.POST.get('student_login_username')
					password = request.POST.get('student_login_password')

					if username.isdigit():
						try:
							instance = ProfessorAuthProfile.objects.filter(mobile_no=username)
							if len(instance) > 1:
								message = 'More than one account is registered with this mobile number.  Kindly use Email-ID to login.'
								messages.warning(request, message)
								return HttpResponseRedirect(reverse('UserAuth:login'))
							else:
								instance = instance[0]
							username = instance.user.username
							user = authenticate(username=username, password=password)
							if user is not None:
								login(request, user)
								return HttpResponseRedirect(reverse('Student:dashboard'))
							messages.warning(request, "Phone No and password doesn't match with any GURUKOOL STUDENT account.")
							return HttpResponseRedirect(reverse('UserAuth:login'))
						except:
							messages.warning(request, "No GURUKOOL STUDENT account is registered with that mobile no.")
							return HttpResponseRedirect(reverse('UserAuth:login'))
					else:
						try:
							match = re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', username)
							if match is None:
								messages.warning(request, 'E-mail entered is not a valid email-address')
								return HttpResponseRedirect(reverse('UserAuth:login'))
							try:
								instance = StudentAuthProfile.objects.get(email_address=username)
							except:
								messages.warning(request, 'No GURUKOOL STUDENT account registered with this email-address.')
								return HttpResponseRedirect(reverse('UserAuth:login'))
							user = authenticate(username=username, password=password)
							if user is not None:
								login(request, user)
								return HttpResponseRedirect(reverse('Student:dashboard'))
							messages.warning(request, "Email address and Password does not match to any GURUKOOL STUDENT Account")
							return HttpResponseRedirect(reverse('UserAuth:login'))
						except:
							messages.error(request, 'BAD REQUEST')
							return HttpResponseRedirect(reverse(settings.MESSAGE_URL))
				else:
					messages.error(request, 'BAD REQUEST')
					return HttpResponseRedirect(reverse(settings.MESSAGE_URL))
			else:
				messages.error(request, 'BAD REQUEST')
				return HttpResponseRedirect(reverse(settings.MESSAGE_URL))
		except Exception as e:
			print(e)
			messages.error(request, 'BAD REQUEST')
			return HttpResponseRedirect(reverse(settings.MESSAGE_URL))


class SignUp(View):
	get_signup_template = 'UserAuth/signupPage.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			if request.user.groups.filter(name='Professor').exists():
				return HttpResponseRedirect(reverse('Professor:dashboard'))
			elif request.user.groups.filter(name='Student').exists():
				return HttpResponseRedirect(reverse('Student:dashboard'))
		gender_choices = GenderChoice.objects.all()
		return render(request, self.get_signup_template, {'gender_choices': gender_choices})

	def post(self, request, *args, **kwargs):
		messages.error(request, 'BAD REQUEST')
		return HttpResponseRedirect(reverse(settings.MESSAGE_URL))

class signupUser(View):
	def get(self, request, *args, **kwargs):
		messages.error(request, 'BAD REQUEST')
		return HttpResponseRedirect(reverse(settings.MESSAGE_URL))

	def post(self, request, *args, **kwargs):
		try:
			type_of_user = kwargs.get('type', None)

			if type_of_user == 'professor':
				first_name = request.POST.get('professor_signup_first_name')
				middle_name = request.POST.get('professor_signup_middle_name')
				last_name = request.POST.get('professor_signup_last_name')
				email = request.POST.get('professor_signup_email')
				mobile_no = request.POST.get('professor_signup_mobile_no')
				date_of_birth = request.POST.get('professor_signup_date_of_birth')
				gender = request.POST.get('professor_signup_gender')
				password = request.POST.get('professor_signup_password')

				otp = randint(100000, 999999)
				email_verification_link = ''.join([choice(string.ascii_letters + string.digits) for n in range(EMAIL_VERIFICATION_LINK_LENGTH)])

				if User.objects.filter(is_superuser=False, email=email).count() > 0:
					messages.warning(request, 'user already signed up with this email')
					return HttpResponseRedirect(reverse('UserAuth:signup'))
				else:
					gender = GenderChoice.objects.get(name=gender)

					user_instance = User()
					user_instance.username = email
					user_instance.first_name = first_name
					user_instance.middle_name = middle_name
					user_instance.last_name = last_name
					user_instance.email = email
					user_instance.set_password(password)
					user_instance.save()

					group = Group.objects.get(name='Professor')
					group.user_set.add(user_instance)

					professor_auth_profile_instance = ProfessorAuthProfile()
					professor_auth_profile_instance.user = user_instance

WEBSITE-master/UserAuth/templates/UserAuth/landingPage.html
{% include 'UserAuth/message.html' %}

landing page here
<br>
<a href="{% url 'UserAuth:login' %}">Login Here</a>
<br>

<!-- <a href="{% url 'UserAuth:signup' %}">SignUp Here</a> -->
<a href="https://serene-wildwood-35121.herokuapp.com/login/5bd09a7e89128700158c1e94">Login with Common APi</a>

WEBSITE-master/UserAuth/templates/UserAuth/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <meta charset="utf-8">
    <title>Gurukool</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
   ================================================== -->
    <link rel="stylesheet" href="{% static 'UserAuth/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'UserAuth/css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'UserAuth/css/main.css' %}">

    <!-- script
   ================================================== -->
    <script src="{% static 'UserAuth/js/modernizr.js' %}"></script>
    <script src="{% static 'UserAuth/js/pace.min.js' %}"></script>

    <!-- favicons
	================================================== -->
    <link rel="shortcut icon" href="https://upload.wikimedia.org/wikipedia/en/thumb/4/49/IIIT_Sri_City_Logo.png/220px-IIIT_Sri_City_Logo.png" type="image/x-icon">
    <link rel="icon" href="https://upload.wikimedia.org/wikipedia/en/thumb/4/49/IIIT_Sri_City_Logo.png/220px-IIIT_Sri_City_Logo.png type="image/x-icon">

</head>

<body id="top">

    <!-- header
   ================================================== -->
   <header id="header" class="row">
   		<div class="header-logo">
	        <a href="index.html">Gurukool</a>
	    </div>
	   	<nav id="header-nav-wrap">
			<ul class="header-main-nav">
				<li class="current"><a class="smoothscroll"  href="#home" title="home">Home</a></li>
			</ul>
            <a href="#" title="sign-up" class="button button-primary cta">Log In</a>
		</nav>
		<a class="header-menu-toggle" href="#"><span>Menu</span></a>
   </header>

   <section id="home" data-parallax="scroll" data-image-src="{% static 'UserAuth/images/hero-bg.jpg' %}">
        <div class="home-content">
            <div class="row contents">
                <div class="home-content-left">
                    <h3 data-aos="fade-up">Welcome to Gurukool</h3>
                    <h1 data-aos="fade-up">
                        Creative Landing <br>
                        Page to Showcase <br>
                        Your Amazing App.
                    </h1>
                    <div class="buttons" data-aos="fade-up">
                        <a href="#download" class="smoothscroll button stroke">
                            <!-- <span class="icon-sign-in" aria-hidden="true"></span> -->
                            <i class="fa fa-sign-in"></i>
                            IIITS LOGIN
                        </a>
                    </div>

                </div>
                <div class="home-image-right">
                    <img src="{% static 'UserAuth/images/iphone-app-470.png' %}">
                </div>
            </div>
        </div>
        hjbjhbjbh
    </section>

    <script src="{% static 'UserAuth/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'UserAuth/js/plugins.js' %}"></script>
    <script src="{% static 'UserAuth/js/main.js' %}"></script>

</body>

</html>

WEBSITE-master/UserAuth/templates/UserAuth/loginPage.html
{% include 'UserAuth/message.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
  <link rel="stylesheet" href="css/style.css">
  <title>Professor Login</title>
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
    <div class="container">
      <a href="index.html" class="navbar-brand"> <img src="https://p7.hiclipart.com/preview/494/348/840/flame-fire-logo-flame.jpg" style="width: 32px; height: 32px; margin-right: 8px;">LeFlame</a>
    </div>
  </nav>

  <!-- HEADER -->
  <header id="main-header" class="py-2 bg-primary text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>
            <i class="fas fa-user"></i> Professor Login</h1>
        </div>
      </div>
    </div>
  </header>

  <!-- ACTIONS -->
  <section id="actions" class="py-4 mb-4 bg-light">
    <div class="container">
      <div class="row">

      </div>
    </div>
  </section>

  <!-- LOGIN -->
  <section id="login">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header">
              <h4>Account Login</h4>
            </div>
            <div class="card-body">
              <form action="{% url 'UserAuth:login-user' 'professor' %}" method="POST">
								{% csrf_token %}
								<div class="form-group">
                  <label for="email">Email</label>
                  <input type="text" class="form-control" name="professor_login_username" required>
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" name="professor_login_password" required>
                </div>
                <input type="submit" value="SUBMIT" class="btn btn-primary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
	<!-- <form action= >

		Email : <input type="text" placeholder="email or phone no" ><br>
		Password : <input type="password" ><br>
		<input type="submit" value="">
	</form> -->
  <!-- FOOTER -->
  <footer id="main-footer" class="bg-dark text-white mt-5 p-5">
    <div class="container">
      <div class="row">
        <div class="col">
          <p class="lead text-center">
            Copyright &copy;
            <span id="year"></span>
          </p>
        </div>
      </div>
    </div>
  </footer>

  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>


  <script>
    // Get the current year for the copyright
    $('#year').text(new Date().getFullYear());
  </script>
</body>

</html>

<!-- Student Login -->

<!-- <form action="{% url 'UserAuth:login-user' 'student' %}" method="POST">
	{% csrf_token %}
	Email : <input type="text" placeholder="email or phone no" name="student_login_username" required><br>
	Password : <input type="password" name="student_login_password" required><br>
	<input type="submit" value="SUBMIT">
</form> -->

WEBSITE-master/UserAuth/templates/UserAuth/message.html
<html>
	<head>
		<style>
			.warning{
				background-color: #ECADAD;
				border-color: red;
				border: 5px;
			}

			.success{
				background-color: #B6ECAD;
				border-color: green;
				border: 5px;
			}
		</style>
	</head>
	<body>
		{% if messages %}
			{% for message in messages %}
				<div class="{{ message.tags }}">{{ message }}</div>
			{% endfor %}
		{% endif %}
	</body>
</html>

WEBSITE-master/UserAuth/templates/UserAuth/signupPage.html
<html>
	<head>
		<title>Sign Up</title>
	</head>
	<body>

		{% include 'UserAuth/message.html' %}

		Professor Sign Up
		<br><br>
		<form action="{% url 'UserAuth:signup-user' 'professor' %}" method="POST" onsubmit="return validateForm('professor')">
			{% csrf_token %}
			First Name : <input type="text" name="professor_signup_first_name" required>
			Middle Name : <input type="text" name="professor_signup_middle_name">
			Last Name : <input type="text" name="professor_signup_last_name" required>
			<br>
			Email : <input type="email" name="professor_signup_email" required>
			<br>
			Mobile No : <input type="number" name="professor_signup_mobile_no" required>
			<br>
			Date of Birth : <input type="date" name="professor_signup_date_of_birth" required>
			<br>
			Gender :
				<br>
				{% for gender in gender_choices %}
					<input type="radio" name="professor_signup_gender" value="{{ gender.name }}"> {{ gender.name }} &nbsp; &nbsp;
				{% endfor %}
			<br>
			Password : <input type="password" name="professor_signup_password" required id="professor_signup_password"><br>
			Confirm Password : <input type="password" name="professor_signup_confirm_password" required id="professor_signup_confirm_password">
			<input type="submit" value="SUBMIT">
		</form>

		<br><br>

		Student Sign Up
		<br><br>
		<form action="{% url 'UserAuth:signup-user' 'student' %}" method="POST" onsubmit="return validateForm('student')">
			{% csrf_token %}
			First Name : <input type="text" name="student_signup_first_name" required>
			Middle Name : <input type="text" name="student_signup_middle_name">
			Last Name : <input type="text" name="student_signup_last_name" required>
			<br>
			Email : <input type="email" name="student_signup_email" required>
			<br>
			Mobile No : <input type="number" name="student_signup_mobile_no" required>
			<br>
			Date of Birth : <input type="date" name="student_signup_date_of_birth" required>
			<br>
			Gender :
				<br>
				{% for gender in gender_choices %}
					<input type="radio" name="student_signup_gender" value="{{ gender.name }}"> {{ gender.name }} &nbsp; &nbsp;
				{% endfor %}
			<br>
			Password : <input type="password" name="student_signup_password" required><br>
			Confirm Password : <input type="password" name="student_signup_confirm_password" required>
			<input type="submit" value="SUBMIT">
		</form>
	</body>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script>
		function validateForm(type)
		{
			if(type == 'professor')
				if($('#professor_signup_password').val() == $('#professor_signup_confirm_password').val())
					return true;
				else
				{
					alert('Passwords Do Not Match');
					return false;
				}
			else if(type == 'student')
				if($('$student_signup_password').val() == $('#student_signup_confirm_password').val())
					return true;
				else
				{
					alert('Passwords Do Not Match');
					return false;
				}
		}
	</script>
</html>