WEBSITE-master/Api/urls.py
from django.conf.urls import include, url
from .views import *
from . import views

app_name = 'Api'

urlpatterns = [
		url(r'^login/$', Login.as_view(), name='login'),
		url(r'^courses/(?P<type>[\w\-]+)/(?P<menu>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CourseList.as_view(), name='course-list'),
        url(r'^doubts/(?P<course_id>\d+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', DoubtCreate.as_view(), name='doubt'),
		url(r'^courses/(?P<course_id>\d+)/doubts/$', CourseDoubt.as_view(), name='course-doubt'),
		url(r'^comments/(?P<doubt_id>\d+)/$', CommentCreate.as_view(), name='comment'),
		url(r'^quiz-details/(?P<quiz_id>[\w\-]+)/$', QuizDetails.as_view(), name='quiz-details'),
		url(r'^check-quiz/(?P<quiz_id>[\w\-]+)/(?P<course_id>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CheckQuiz.as_view(), name='check-quiz'),
		url(r'^comment-on-doubt/$', CommentOnDoubt.as_view(), name='comment-on-doubt'),
		url(r'^quiz-complete/$', QuizComplete.as_view(), name='quiz-complete'),
		url(r'^meeting/(?P<type>[\w\-]+)/$',MeetingManage.as_view(), name='meeting-create'),
		url(r'^all-student-quizes/(?P<course_id>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',AllStudentQuiz.as_view(), name='all-student-quizes'),
		url(r'^create-meeting/(?P<course_id>\d+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CreateMeeting.as_view(), name='create-meeting'),	
		
		url(r'^calling-stored-procedure/$', views.CallingStoredProcedure, name='calling-stored-procedure'),	
		
		# url(r'^test/$', views.Test, name='test'),
	]

WEBSITE-master/Doubt/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'Doubt'

urlpatterns = [
    url(r'^course/(?P<course_id>\d+)/$', views.show_doubt, name='doubt-list'),
    url(r'^doubt-detail/(?P<doubt_id>\d+)/$', views.doubt, name='doubt'),
    url(r'^post-comment/(?P<doubt_id>\d+)/$', views.create_comment, name='post-comment'),
    url(r'^$', views.all_doubts, name='index'),
]

WEBSITE-master/Professor/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'Professor'

urlpatterns = [
		url(r'^$', views.dashboard, name='dashboard'),
		url(r'^can_view/$', views.can_view, name='can_view'),
		url(r'^create-poll/$', views.create_poll, name='create-poll'),
		url(r'^poll/(?P<poll_id>\d+)/$', views.show_poll, name='poll'),
		url(r'^poll/$', views.show_all_polls, name='all-poll'),
		url(r'^quiz/$', views.show_all_quiz, name='all-quiz'),
		url(r'^create-quiz/$', views.create_quiz, name='create-quiz'),
		url(r'^quiz/(?P<quiz_id>\d+)/$', views.show_quiz, name='quiz'),
		url(r'^conduct-quiz/(?P<quiz_id>\d+)/$', views.conduct_quiz, name='conduct-quiz'),
		url(r'^stop-quiz/(?P<quiz_id>\d+)/$', views.stop_quiz, name='stop-quiz'),
		url(r'^conduct-poll/(?P<poll_id>\d+)/$', views.conduct_poll, name='conduct-poll'),
		url(r'^stop-poll/(?P<poll_id>\d+)/$', views.stop_poll, name='stop-poll'),
		url(r'^conducted-poll/(?P<poll_id>\d+)/$', views.conducted_poll, name='conducted-poll'),
		url(r'^conducted-quiz/(?P<quiz_id>\d+)/$', views.conducted_quiz, name='conducted-quiz'),
		url(r'^quiz-result/(?P<quiz_id>\d+)/$', views.quiz_result, name='quiz-result'),
		url(r'^view-quiz-responses/(?P<quiz_id>\d+)/$', views.view_quiz_reponses, name='view-quiz-responses'),
		url(r'^question-wise-result/$', views.question_wise_result, name='question-wise-result'),
		url(r'^quiz-result-pdf/(?P<quiz_id>\d+)/$', views.quiz_result_pdf, name='quiz-result-pdf'),
		url(r'^quiz-result-csv/(?P<quiz_id>\d+)/$', views.quiz_result_csv, name='quiz-result-csv'),

		url(r'^test/$', views.test, name='test'),

	]

WEBSITE-master/Student/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'Student'

urlpatterns = [
		url(r'^$', views.dashboard, name='dashboard'),
		url(r'^(?P<student_id>\d+)/$', views.profile, name='profile'),
	]

WEBSITE-master/gurukool_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('UserAuth.urls', namespace='UserAuth')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^professor/', include('Professor.urls', namespace="Professor")),
	url(r'^student/', include('Student.urls', namespace="Student")),
    url(r'^api/', include('Api.urls', namespace="Api")),
    url(r'^doubt/', include('Doubt.urls', namespace="Doubt")),
    url(r'^meeting/', include('Meeting.urls', namespace="Meeting")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WEBSITE-master/Doubt/models.py
from django.db import models
from django.contrib.auth.models import User

from Student.models import StudentProfile
from Professor.models import Course


class Doubt(models.Model):
	student = models.ForeignKey(StudentProfile, on_delete=models.SET_NULL, null=True)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	title = models.CharField(max_length=100, null=False, blank=False)
	description = models.CharField(max_length=1000, null=False, blank=False)
	last_updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "{}: {}".format(self.course.name, self.title)


class Comment(models.Model):
	doubt = models.ForeignKey(Doubt, on_delete=models.CASCADE, null=False)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
	text = models.CharField(max_length=1000, null=False, blank=False)
	last_updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "{}: {} - {}".format(self.doubt.title, self.text, self.user.username)

WEBSITE-master/Doubt/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from .models import *
from Professor.models import Course
from Professor.models import *

student_group = 'Student'
prof_group = 'Professor'
login_url = 'UserAuth:login'

def group_required(*group_names, login_url=None):
    ''' checks group requirement whwther the user is student or professor
        Takes group name as input and login url
        returns status if user passes or not'''
    def in_groups(u):
        if u.is_authenticated:
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False
    return user_passes_test(in_groups, login_url=login_url)

''' login required'''
@login_required(login_url=login_url)
@group_required(prof_group, login_url=login_url)
def show_doubt(request, course_id):
    '''
        Shows all Doubts
        Takes input course_id,request
        Returns doubt_list,course and renders the web page
    '''
    if request.method == 'GET':
        doubts = Doubt.objects.filter(course__id=course_id)
        course = Course.objects.get(id=course_id)
        return render(request, 'Doubt/doubt.html', {"doubt_list": doubts, "course":course})

@login_required(login_url=login_url)
def create_comment(request, doubt_id):
    '''
       Creates a new comment
       Takes input request method and doubt_id
       returns http response if comment created successfuly 
    '''
    if request.method == 'POST':
        text = request.POST['comment']
        doubt = Doubt.objects.get(id=doubt_id)
        comment = Comment.objects.create(doubt=doubt, user_id=request.user.id, text=text)
        # return HttpResponseRedirect(reverse('Doubt:doubt-list',kwargs={'course_id':doubt.course.id}))
        return HttpResponseRedirect(reverse('Doubt:doubt', kwargs={'doubt_id': doubt_id}))

'''
Get a particular doubt
Takes input request method and doubt_id
Returns doubt_data,previous_replies and renders the web page
'''
@login_required(login_url=login_url)
@group_required(prof_group, login_url=login_url)
def doubt(request, doubt_id):
        if request.method == 'GET':
                try:
                        doubt = Doubt.objects.get(id=doubt_id)
                        previous_replies = Comment.objects.filter(doubt__id=doubt_id).order_by('-last_updated')
                        return render(request, 'Doubt/doubt-details.html', {"doubt_data": doubt, "previous_replies": previous_replies})
                except Exception as e:
                        print(e)
                        messages.success(request, "Some Error Occurred")
                        return HttpResponseRedirect(reverse('Professor:dashboard'))

@login_required(login_url=login_url)
@group_required(prof_group, login_url=login_url)
def all_doubts(request):
        if request.method == 'GET':
                course_list = CourseProfessor.objects.filter(professor__user__user__id=request.user.id).order_by('-id')
                all_doubt_list = []
                for course in course_list:
                        for y in Doubt.objects.filter(course__id=course.course.id):
                                all_doubt_list.append(y)
                all_doubt_list = sorted(all_doubt_list, key=lambda k: k.last_updated)
                all_doubt_list = all_doubt_list[::-1]

                return render(request, 'Doubt/all-doubts.html', {'all_doubt_list': all_doubt_list})

WEBSITE-master/Doubt/templates/Doubt/all-doubts.html
{% extends 'Professor/main.html' %}
{% include 'UserAuth/message.html' %}
{% load staticfiles %}

{% block title %}
    Doubts
{% endblock %}

{% block body %}

<section class="body-section">
        <div class="container">
            <div class="row">
    
                <div class="card col-md-12 col-xs-12 all-meeting-card">
                            <div class="card-header">
                                <div class="row">
                                    {% if all_doubt_list %}
                                    <div class="col-md-8 col-xs-12">Doubts - {{ all_doubt_list|length }}</div>
                                    {% else %}
                                    <div class="col-md-8 col-xs-12">Doubts</div>
                                    {% endif %}
                                    <!-- <div class="col-md-2 col-xs-12"><a href="{% url 'Professor:create-quiz' %}"><button type="button" class="btn btn-info btn-sm">Add Quiz</button></a></div>
                                    <div class="col-md-2 col-xs-12"><a href="{% url 'Professor:all-quiz' %}"><button type="button" class="btn btn-info btn-sm">View All</button></a></div> -->
                                </div>
                            </div>
                            <div class="card-body" style="overflow-y: scroll;">
                                <div class="row">
                                    {% if all_doubt_list %}
                                    {% for doubt in all_doubt_list %}
                                    <div class="col-md-4 col-xs-12">
                                    <div class="card meeting-card border-primary">
                                            <div class="card-header">
                                                <div class="row">
                                                    <div class="col-md-9 col-xs-12">{{ doubt.course.code }}</div>
                                                    <div class="col-md-3 col-xs-12">
                                                        <a href="{% url 'Doubt:doubt' doubt.id %}" style="text-decoration: underline; color: black">Info</a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-body meeting-card-body" style="overflow-y: scroll">
                                                <div class="row">
                                                    <div class="col-md-4 col-xs-12"><img src="{% static 'images/avatar/student.png' %}" class="student-avatar"></div>
                                                    <div class="col-md-8 col-xs-12">{{ doubt.student.user.user.first_name }} {{ doubt.student.user.user.last_name }}</div>
                                                </div>
                                                <p class="card-text meeting-title">{{ doubt.title }}</p>
                                                <p class="card-text meeting-body">{{ doubt.description }}</p>
                                            </div>
                                            <div class="card-footer">
                                                <div class="row">
                                                    <div class="col-md-8 col-xs-12"><small class="text-muted">{{ doubt.last_updated }}</small></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    {% else %}
                                    <div class="col-md-12 col-xs-12">
                                            <div class="card quiz-card">
                                                <div class="card-body quiz-card-body" style="overflow-y: scroll;">
                                                    No Doubts
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}
{% endblock %}

WEBSITE-master/Doubt/templates/Doubt/doubt-details.html
{% extends 'Professor/main.html' %}
{% load tags %}
{% load staticfiles %}

{% block title %}
    Quiz Detail
{% endblock %}

{% block body %}
    <!-- Quiz Detail Here {{ quiz_data.0.quiz.id }}<br><br> -->

  {% include 'UserAuth/message.html' %}

    <!-- <header id="main-header" class="py-2 bg-success text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1> <a href="{% url 'Professor:dashboard' %}"><i class="fa fa-arrow-left" style="color: white"></i></a> Doubt Detail</h1>
        </div>
      </div>
    </div>
  </header>

  <section id="categories">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
                <h4>
                    <div class="row">
                        <div class="col-md-10">{{ doubt_data.course.name }} - {{ doubt_data.course.code }}</div>
                    </div>
            </h4>
            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                  <th>{{ doubt_data.title }}</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ doubt_data.description }}</td>
                </tr>
                <tr>
                    <td>Posted By :  <b>{{doubt_data.student.user.user.first_name}} {{doubt_data.student.user.user.last_name}}</b></td>
                  </tr>
                  <tr>
                    <td>Posted On: <b>{{ doubt_data.last_updated }}</b></td>
                  </tr>

              </tbody>
            </table>
          </div>
          </div>

          <form action="{% url 'Doubt:post-comment' doubt_data.id %}" id="comment-submit" method="POST">
              {% csrf_token %}
          <section id="details">
                <div class="container">
                  <div class="row">
                    <div class="col">
                      <div class="card">
                        <div class="card-header">
                          <h4>
                            <div class="row">
                                <div class="col-md-10">Doubt</div>
                                <div class="col-md-2"><button type="submit" class="btn btn-success btn-block" style="background-color: #555555;"> <i class="fa fa-check"></i> &nbsp; &nbsp;Submit</button></div>
                            </div>
                          </h4>
                        </div>
                        {% for reply in previous_replies %}
                            {% if reply.user.email == request.user.email %}
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="card-body col-md-8">
                                    <div class="form-group">
                                        <label>{{ reply.last_updated }}</label>
                                        <textarea readonly class="form-control" required>{{ reply.text }}</textarea>
                                    </div>
                                </div>
                            </div>
                            {% else %}
                            <div class="row">
                                <div class="card-body col-md-8">
                                    <div class="form-group">
                                            <label>{{ reply.last_updated }}</label>
                                        <textarea readonly class="form-control" required>{{ reply.text }}</textarea>
                                    </div>
                                </div>
                                <div class="col-md-4"></div>
                            </div>
                            {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <div class="form-group">
                                <label for="body">Reply</label>
                                <textarea name="comment" class="form-control" rows=4 required></textarea>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              </form> -->

              <section class="body-section">
                  <div class="container">
                      <div class="row">
                          <div class="col-md-12 col-xs-12">
                            <div class="card active-quiz-card border-primary">
                              <div class="card-header">
                                <div class="row">
                                    <div class="col-md-9 col-xs-12">Doubt Detail</div>
                                    <div class="col-md-3 col-xs-12">{{ meeting.created_time }}</div>
                                  </div>
                              </div>
                              <div class="card-body">
                                <div class="row">
                                  <div class="col-md-6 col-xs-12">
                                      <div class="row">
                                          <div class="col-md-6 col-xs-12"><strong>Course Code</strong></div>
                                          <div class="col-md-6 col-xs-12">{{ doubt_data.course.code }}</div>
                                      </div>
                                      <div class="row">
                                          <div class="col-md-6 col-xs-12"><strong>Title</strong></div>
                                          <div class="col-md-6 col-xs-12">{{ doubt_data.title }}</div>
                                      </div>
                                    <div class="row">
                                      <div class="col-md-6 col-xs-12"><strong>Posted By</strong></div>
                                      <div class="col-md-6 col-xs-12">{{doubt_data.student.user.user.first_name}} {{doubt_data.student.user.user.last_name}}</div>
                                    </div>
                                  </div>
                                  <div class="col-md-6 col-xs-12">
                                    <div class="row">
                                      <div class="col-md-6 col-xs-12"><strong>Course Name</strong></div>
                                      <div class="col-md-6 col-xs-12">{{ doubt_data.course.name }}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6 col-xs-12"><strong>Description</strong></div>
                                        <div class="col-md-6 col-xs-12">{{ doubt_data.description }}</div>
                                      </div>
                                      <div class="row">
                                          <div class="col-md-6 col-xs-12"><strong>Posted On</strong></div>
                                          <div class="col-md-6 col-xs-12">{{ doubt_data.last_updated }}</div>
                                        </div>
                                  </div>
                                </div>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                      <form action="{% url 'Doubt:post-comment' doubt_data.id %}" id="comment-submit" method="POST">
                          {% csrf_token %}
                      <section id="details">
                            <div class="container">
                              <div class="row">
                                <div class="col">
                                  <div class="card">
                                    <div class="card-header">
                                      <h4>
                                        <div class="row">
                                            <div class="col-md-10">Doubt</div>
                                            <div class="col-md-2"><button type="submit" class="btn btn-success btn-block" style="background-color: #555555;"> <i class="fa fa-check"></i> &nbsp; &nbsp;Submit</button></div>
                                        </div>
                                      </h4>
                                    </div>
                                    {% for reply in previous_replies %}
                                        {% if reply.user.email == request.user.email %}
                                        <div class="row">
                                            <div class="col-md-4"></div>
                                            <div class="card-body col-md-8">
                                                <div class="form-group">
                                                    <label>{{ reply.last_updated }}</label>
                                                    <textarea readonly class="form-control" required>{{ reply.text }}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                        {% else %}
                                        <div class="row">
                                            <div class="card-body col-md-8">
                                                <div class="form-group">
                                                        <label>{{ reply.last_updated }}</label>
                                                    <textarea readonly class="form-control" required>{{ reply.text }}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-md-4"></div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="body">Reply</label>
                                            <textarea name="comment" class="form-control" rows=4 required></textarea>
                                        </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </section>
                          </form>
            </section>


  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        


{% endblock %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
{% endblock %}

WEBSITE-master/Doubt/templates/Doubt/doubt.html
{% extends 'Professor/main.html' %}
{% load staticfiles %}

{% block title %}
    Doubts
{% endblock %}

{% block body %}
    {% include 'UserAuth/message.html' %}
    <h1>Course: {{course.name}} - {{course.code}}</h1>
    <br>
    <h2>All Doubts:</h2><br><br>

    {% if doubt_list %}
      <ul>
      {% for doubt in doubt_list %}
        <li>
          <h4>{{doubt.title}}</h4>
          <h5>{{doubt.description}}</h5>
          Posted by: {{doubt.student.user.user.first_name}} {{doubt.student.user.user.last_name}}
          Last updated: {{doubt.last_updated}}
          <br>

          <form action="#" id="comment-submit"  method="POST">
            {% csrf_token %}
            <textarea name="text" rows="3" cols="50" placeholder="Write your comment here and make post request to {% url 'Api:comment' doubt.id %}" required></textarea>
            <input type="submit" value="SUBMIT">
          </form>
          To get all comments for the doubt post, make a get request to {% url 'Api:comment' doubt.id %}
          <br><br>
        </li>
      {% endfor %}
      </ul>
    {% else %}
      No doubts posted
    {% endif %}
{% endblock %}




{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}