WEBSITE-master/Api/urls.py
from django.conf.urls import include, url
from .views import *
from . import views

app_name = 'Api'

urlpatterns = [
		url(r'^login/$', Login.as_view(), name='login'),
		url(r'^courses/(?P<type>[\w\-]+)/(?P<menu>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CourseList.as_view(), name='course-list'),
        url(r'^doubts/(?P<course_id>\d+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', DoubtCreate.as_view(), name='doubt'),
		url(r'^courses/(?P<course_id>\d+)/doubts/$', CourseDoubt.as_view(), name='course-doubt'),
		url(r'^comments/(?P<doubt_id>\d+)/$', CommentCreate.as_view(), name='comment'),
		url(r'^quiz-details/(?P<quiz_id>[\w\-]+)/$', QuizDetails.as_view(), name='quiz-details'),
		url(r'^check-quiz/(?P<quiz_id>[\w\-]+)/(?P<course_id>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CheckQuiz.as_view(), name='check-quiz'),
		url(r'^comment-on-doubt/$', CommentOnDoubt.as_view(), name='comment-on-doubt'),
		url(r'^quiz-complete/$', QuizComplete.as_view(), name='quiz-complete'),
		url(r'^meeting/(?P<type>[\w\-]+)/$',MeetingManage.as_view(), name='meeting-create'),
		url(r'^all-student-quizes/(?P<course_id>[\w\-]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',AllStudentQuiz.as_view(), name='all-student-quizes'),
		url(r'^create-meeting/(?P<course_id>\d+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', CreateMeeting.as_view(), name='create-meeting'),	
		
		url(r'^calling-stored-procedure/$', views.CallingStoredProcedure, name='calling-stored-procedure'),	
		
		# url(r'^test/$', views.Test, name='test'),
	]

WEBSITE-master/Doubt/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'Doubt'

urlpatterns = [
    url(r'^course/(?P<course_id>\d+)/$', views.show_doubt, name='doubt-list'),
    url(r'^doubt-detail/(?P<doubt_id>\d+)/$', views.doubt, name='doubt'),
    url(r'^post-comment/(?P<doubt_id>\d+)/$', views.create_comment, name='post-comment'),
    url(r'^$', views.all_doubts, name='index'),
]

WEBSITE-master/Professor/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'Professor'

urlpatterns = [
		url(r'^$', views.dashboard, name='dashboard'),
		url(r'^can_view/$', views.can_view, name='can_view'),
		url(r'^create-poll/$', views.create_poll, name='create-poll'),
		url(r'^poll/(?P<poll_id>\d+)/$', views.show_poll, name='poll'),
		url(r'^poll/$', views.show_all_polls, name='all-poll'),
		url(r'^quiz/$', views.show_all_quiz, name='all-quiz'),
		url(r'^create-quiz/$', views.create_quiz, name='create-quiz'),
		url(r'^quiz/(?P<quiz_id>\d+)/$', views.show_quiz, name='quiz'),
		url(r'^conduct-quiz/(?P<quiz_id>\d+)/$', views.conduct_quiz, name='conduct-quiz'),
		url(r'^stop-quiz/(?P<quiz_id>\d+)/$', views.stop_quiz, name='stop-quiz'),
		url(r'^conduct-poll/(?P<poll_id>\d+)/$', views.conduct_poll, name='conduct-poll'),
		url(r'^stop-poll/(?P<poll_id>\d+)/$', views.stop_poll, name='stop-poll'),
		url(r'^conducted-poll/(?P<poll_id>\d+)/$', views.conducted_poll, name='conducted-poll'),
		url(r'^conducted-quiz/(?P<quiz_id>\d+)/$', views.conducted_quiz, name='conducted-quiz'),
		url(r'^quiz-result/(?P<quiz_id>\d+)/$', views.quiz_result, name='quiz-result'),
		url(r'^view-quiz-responses/(?P<quiz_id>\d+)/$', views.view_quiz_reponses, name='view-quiz-responses'),
		url(r'^question-wise-result/$', views.question_wise_result, name='question-wise-result'),
		url(r'^quiz-result-pdf/(?P<quiz_id>\d+)/$', views.quiz_result_pdf, name='quiz-result-pdf'),
		url(r'^quiz-result-csv/(?P<quiz_id>\d+)/$', views.quiz_result_csv, name='quiz-result-csv'),

		url(r'^test/$', views.test, name='test'),

	]

WEBSITE-master/Student/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'Student'

urlpatterns = [
		url(r'^$', views.dashboard, name='dashboard'),
		url(r'^(?P<student_id>\d+)/$', views.profile, name='profile'),
	]

WEBSITE-master/UserAuth/urls.py
from django.conf.urls import include, url
from . import views
from . import utils
from django.contrib.auth import logout

app_name = 'UserAuth'

urlpatterns = [
		url(r'^$', views.landingPage.as_view(), name='landingPage'),
		url(r'^login/$', views.Login.as_view(), name='login'),
		url(r'^signup/$', views.SignUp.as_view(), name='signup'),
		url(r'^signup-user/(?P<type>[\w\-]+)$', views.signupUser.as_view(), name='signup-user'),
		url(r'^login-user/(?P<type>[\w\-]+)', views.LoginUser.as_view(), name='login-user'),
		url(r'^send-verification-data/(?P<user_group>[\w\-]+)/(?P<send_to>[\w\-]+)$', views.send_verification_data, name='send-verification-data'),

		url(r'^show-message/$', utils.show_message, name='show-message'),

		url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
		url(r'^auth/callback/(?P<user_token>.+)$', views.redirectPage, name='redirection'),
	]

# Our Client Id and Client Key
# "_id": "5bd09a7e89128700158c1e94",
#     "email": "anurag.g16@iiits.in",
#     "group": "B01",
#     "callback": "localhost:8000/auth/callback/",
#     "__v": 0,
#     "clientSecret": "27da906cca2278407c4717551f8ccae5d2fb89da47009050f3671245f2a14440f9c282152877f7d6b08d3f19696d94844b9f74ac901752424045f9190910d0bd"

WEBSITE-master/gurukool_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('UserAuth.urls', namespace='UserAuth')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^professor/', include('Professor.urls', namespace="Professor")),
	url(r'^student/', include('Student.urls', namespace="Student")),
    url(r'^api/', include('Api.urls', namespace="Api")),
    url(r'^doubt/', include('Doubt.urls', namespace="Doubt")),
    url(r'^meeting/', include('Meeting.urls', namespace="Meeting")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WEBSITE-master/Professor/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
import UserAuth.utils as UserAuthutils
from django.conf import settings
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import *
from Doubt.models import *
from Student.models import *
from Meeting.models import *
import hashlib
import time, csv
import datetime
from django.db.models import Count
from .utils import *
from django.http import StreamingHttpResponse

group_name = 'Professor'
login_url = 'UserAuth:login'

class Echo:
    """An object that implements just the write method of the file-like
    interface.
    """
    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value

def group_required(*group_names, login_url=None):
    ''' checks group requirement whwther the user is student or professor
        Takes group name as input and login url
        returns status if user passes or not'''
    def in_groups(u):
        if u.is_authenticated:
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False
    return user_passes_test(in_groups, login_url=login_url)

''' Login Required
'''
@login_required(login_url=login_url)
@group_required(group_name, login_url=login_url)
def dashboard(request):
    '''
        Loads all the data for the dashboard. Gets active polls, active quizzes, meetings today and doubts overview
        Takes only input GET request whenever the user goes to the dashboard page
        Returns all_doubt_list,poll_list,quiz_list,course_list,meeting_list,active_quiz_list
    '''
    if request.method == 'GET':
        poll_list = Poll.objects.filter(professor__user__user__username=request.user.username).order_by('-id')
        quiz_list = Quiz.objects.filter(professor__user__user__username=request.user.username).order_by('-id')
        course_list = CourseProfessor.objects.filter(professor__user__user__id=request.user.id).order_by('-id')
        meeting_list = (MeetingPlace.objects.filter(meeting__professor__user__user__id=request.user.id, is_ticked=False, meeting_date=time.strftime('%Y-%m-%d'), meeting__status='APPROVED').order_by('meeting_time'))[:1]
        active_poll_list = ConductPoll.objects.filter(poll__professor__user__user__username=request.user.username, active=True).order_by('-id')
        active_quiz_list = ConductQuiz.objects.filter(quiz__professor__user__user__username=request.user.username, active=True).order_by('-id')
        all_doubt_list = []

        for course in course_list:
            for y in Doubt.objects.filter(course__id=course.course.id):
                all_doubt_list.append(y)
        all_doubt_list = sorted(all_doubt_list, key=lambda k: k.last_updated)
        all_doubt_list = all_doubt_list[::-1]
        all_doubt_list = all_doubt_list[:1]

        for quiz in active_quiz_list:
            quiz.submissions = QuizResult.objects.filter(conduct_quiz=quiz).count()
            quiz.total = CourseStudent.objects.filter(course=quiz.quiz.course).count()

        all_conducted_quiz_stats = QuizStatistics.objects.filter(quiz_id__quiz__professor__user__user__username=request.user.username)
        print(all_conducted_quiz_stats)



        # all_meetings = []
        # meeting_list = (MeetingPlace.objects.filter(meeting__professor__user__user__id=request.user.id, is_ticked=False, meeting_date=time.strftime('%Y-%m-%d'), meeting__status='APPROVED').order_by('meeting_time'))
        # for m in meeting_list:
        #     print(m.meeting_time)
        #     print(datetime.datetime.time(datetime.datetime.now()))
        #     if m.meeting_time >= datetime.datetime.time(datetime.datetime.now()):
        #         print(True)
        #         all_meetings.append(m)
        # print(all_meetings)

        return render(request, 'Professor/dashboard.html', {"quiz_stats": all_conducted_quiz_stats, "all_doubt_list": all_doubt_list, "poll_list": poll_list, "quiz_list": quiz_list, "course_list":course_list, "meeting_list":meeting_list, "active_quiz_list": active_quiz_list, "active_poll_list": active_poll_list})

''' Login Required
'''
@login_required(login_url=login_url)
@group_required(group_name, login_url=login_url)
def create_poll(request):
    '''
        Creates a new Poll. If GET request, then render the web page for adding a poll. If POST request then form submit and adding a poll in database
        Takes only request as input
        if GET request then render the web page for adding a poll. If POST request, add data entries into database and user is redirected to professor
    '''
    if request.method == 'GET':
        course_list = CourseProfessor.objects.filter(professor__user__user__username=request.user.username)
        return render(request, 'Professor/create-poll.html', {'course_list': course_list})

    if request.method == 'POST':
        course = request.POST.get('course')
        title = request.POST.get('title')
        question = request.POST.get('question')
        option_list = request.POST.getlist('poll_options[]')
        try:
            poll_inst = Poll()
            poll_inst.professor = ProfessorProfile.objects.get(user__user__username=request.user.username)
            poll_inst.course = Course.objects.get(id=(CourseProfessor.objects.get(id=course)).course.id)
            poll_inst.title = title
            poll_inst.question = question
            poll_inst.save()
            for option in option_list:
                option_inst = PollOption()
                option_inst.poll = poll_inst
                option_inst.option = option
                option_inst.save()
            messages.success(request, "Successfully created Poll")
            return HttpResponseRedirect(reverse('Professor:all-poll'))
        except Exception as e:
            print(e)
            messages.warning(request, "There was an error creating poll. Please Try Again.")
            return HttpResponseRedirect(reverse('Professor:create-poll'))

''' Login Required
'''
@login_required(login_url=login_url)
@group_required(group_name, login_url=login_url)
def show_poll(request, poll_id):
    '''
        This function is for showing a particular poll
        Takes input the poll_id to get a specific poll and request method.
        Retrieves Poll details and render the web page poll-detail.html with variables poll_details,poll_options,is_poll_active.
    '''
    if request.method == 'GET':
        poll_details = Poll.objects.get(id=poll_id)
        poll_options = PollOption.objects.filter(poll__id=poll_id)
        is_poll_active = ConductPoll.objects.filter(active=True, poll__id=poll_id)
        return render(request, 'Professor/poll-detail.html', {"poll_details": poll_details, 'poll_options': poll_options, "is_poll_active": is_poll_active})

''' Login Required
'''
@login_required(login_url=login_url)
@group_required(group_name, login_url=login_url)
def create_quiz(request):
    '''
        Creates a new Quiz. If GET request, then render the web page for adding a quiz. If POST request then form submit and adding a quiz in database
        Takes only request as input
        if GET request then render the web page for adding a poll. If POST request, add data entries into database and user is redirected to professor dashboard
    '''
    if request.method == 'GET':
        course_list = CourseProfessor.objects.filter(professor__user__user__username=request.user.username)
        return render(request, 'Professor/create-quiz.html', {'course_list': course_list})

    if request.method == 'POST':
        try:
            question_option_array = list(map(int, request.POST['question-option'].split(',')))
            quiz = Quiz()
            quiz.professor = ProfessorProfile.objects.get(user__user__username=request.user.username)
            course = CourseProfessor.objects.get(id=int(request.POST['course']))
            quiz.course = Course.objects.get(id=int(course.course.id))
            quiz.title = request.POST['title']
            quiz.description = request.POST['description']
            quiz.max_marks = request.POST['max_marks']
            quiz.pass_marks = request.POST['pass_marks']
            quiz.save()

            question_count = 0
            for i in range(len(question_option_array)):
                if question_option_array[i] != 0:
                    question_count += 1
                    ques_inst = QuizQuestion()
                    ques_inst.quiz = quiz
                    ques_inst.question = request.POST['question_'+str(i+1)]
                    ques_inst.marks = request.POST['marks_'+str(i+1)]
                    ques_inst.time = request.POST['time_'+str(i+1)]
                    ques_inst.save()
                    option_list = request.POST.getlist('poll_options_'+str(i+1)+'[]')
                    for j in range(len(option_list)):
                        opt_inst = QuizOptions()
                        opt_inst.quiz = quiz
                        opt_inst.question = ques_inst
                        opt_inst.option = option_list[j]
                        if request.POST.get('option_checkbox_'+str(i+1)+'_'+str(j+1)) is not None:
                            opt_inst.is_correct = True
                        else:
                            opt_inst.is_correct = False
                        opt_inst.save()
            quiz.no_of_questions = question_count
            quiz.save()
            messages.success(request, "Successfully Created Quiz")
            return HttpResponseRedirect(reverse('Professor:all-quiz'))
        except Exception as e:
            print('error is ', e)
            messages.warning(request, "There was an error creating Quiz. Please Try Again.")

WEBSITE-master/Professor/templates/Professor/quiz-result.html
{% extends 'Professor/main.html' %}
{% load tags %}
{% load staticfiles %}

{% block title %}
    Quiz Results ({{ conducted_quiz.unique_quiz_id }})
{% endblock %}

{% block body %}

  {% include 'UserAuth/message.html' %}

    <section class="body-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <a href="{% url 'Professor:dashboard' %}" class="question-response-count">Dashboard</a>
                    /
                    <a href="{% url 'Professor:all-quiz' %}" class="question-response-count">Quiz</a>
                    / 
                    <a href="{% url 'Professor:conducted-quiz' conducted_quiz.id %}" class="question-response-count">Quiz <strong>{{ conducted_quiz.unique_quiz_id }}</strong></a>
                    /
                    Quiz Results
                </div>
              </div>
            <div class="row">
                <div class="col-md-12 col-xs-12">
                  <div class="card active-quiz-card border-primary">
                    <div class="card-header">
                      <div class="row">
                          <div class="col-md-6 col-xs-12">Quiz Detail ({{ conducted_quiz.unique_quiz_id }})</div>
                          <div class="col-md-3 col-xs-12">{{ conducted_quiz.conduction_date }}</div>
                          <div class="col-md-3 col-xs-12"><a href="{% url 'Professor:view-quiz-responses' conducted_quiz.id %}"><button class="btn btn-info btn-sm"> <i class="fa fa-eye"></i> &nbsp; &nbsp;View Quiz Responses</button></a></div>
                        </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-6 col-xs-12">
                          <div class="row">
                            <div class="col-md-6 col-xs-12"><strong>Course Code</strong></div>
                            <div class="col-md-6 col-xs-12">{{ conducted_quiz.quiz.course.code }}</div>
                          </div>
                          <div class="row">
                            <div class="col-md-6 col-xs-12"><strong>Title</strong></div>
                            <div class="col-md-6 col-xs-12">{{ conducted_quiz.quiz.title }}</div>
                          </div>
                          <div class="row">
                              <div class="col-md-6 col-xs-12"><strong>Maximum Marks</strong></div>
                              <div class="col-md-6 col-xs-12">{{ conducted_quiz.quiz.max_marks }}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-xs-12"><strong>Average Marks</strong></div>
                                <div class="col-md-6 col-xs-12">{{ quiz_statistics.avg|floatformat:2 }}</div>
                              </div>
                        </div>
                        <div class="col-md-6 col-xs-12">
                          <div class="row">
                            <div class="col-md-6 col-xs-12"><strong>Course Name</strong></div>
                            <div class="col-md-6 col-xs-12">{{ conducted_quiz.quiz.course.name }}</div>
                          </div>
                          <div class="row">
                            <div class="col-md-6 col-xs-12"><strong>Description</strong></div>
                            <div class="col-md-6 col-xs-12">{{ conducted_quiz.quiz.description }}</div>
                          </div>
                          <div class="row">
                              <div class="col-md-6 col-xs-12"><strong>Pass Marks</strong></div>
                              <div class="col-md-6 col-xs-12">{{ conducted_quiz.quiz.pass_marks }}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-xs-12"><strong>Total Responses</strong></div>
                                <div class="col-md-6 col-xs-12">{{ quiz_statistics.number_of_responses }}</div>
                              </div>
                        </div>
                      </div>
                      </div>
                    </div>
                </div>
              </div>
              <br>
              <div class="card active-quiz-card border-dark" style="overflow-y: scroll;">
                <div class="card-header">
                    <div class="row">
                      <div class="col-md-9 col-xs-12">Rank List</div>
                      <div class="col-md-3 col-xs-12">
                        <input type="text" id="rank-filter-search" placeholder="Search..." onkeyup="filter_by_keyword(this.value)">&nbsp;
                        <a target="_blank" href="{% url 'Professor:quiz-result-pdf' conducted_quiz.id %}"><i class="fa fa-download" aria-hidden="true" title="Download as PDF" style="color: black;"></i></a>
                        <a target="_blank" href="{% url 'Professor:quiz-result-csv' conducted_quiz.id %}"><i class="fa fa-table" aria-hidden="true" title="Download as CSV" style="color: black;"></i></a>
                      </div>
                    </div>
                </div>
                <div class="card-body">
                  <div class="row" id="rank-list">
                      {% for result in quiz_results %}
                      <div class="col-md-3 col-xs-12 rank-list-card">
                        {% if result.marks_obtained >= conducted_quiz.quiz.pass_marks %}<div class="card meeting-card border-success">{% endif %}
                        {% if result.marks_obtained < conducted_quiz.quiz.pass_marks %}<div class="card meeting-card border-danger">{% endif %}
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-md-9 col-xs-12 marks-obtained">{{ result.marks_obtained }}</div>
                                    <div class="col-md-3 col-xs-12 student-rank">#{{forloop.counter}}</div>
                                </div>
                            </div>
                            <div class="card-body meeting-card-body" style="overflow-y: scroll">
                                <div class="row">
                                    <div class="col-md-4 col-xs-12"><img src="{% static 'images/avatar/student.png' %}" class="student-avatar"></div>
                                    <div class="col-md-8 col-xs-12"><a target="_blank" href="{% url 'Student:profile' result.student.user.user.id %}" class="question-response-count student-name">{{ result.student.user.user.first_name }} {{ result.student.user.user.last_name }}</a></div>
                                </div>
                            </div>
                        </div>
                      </div>
                      {% endfor %}
                      <!-- <table class="table table-striped">
                          {% if quiz_results %}
                          <thead class="card-header">
                          <tr>
                            <th>Rank</th>
                            <th>Roll No.</th>
                            <th>Name</th>
                            <th>Marks</th>
                            <th>Status</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for result in quiz_results %}
                            <tr class="rank-list-card">
                              <td class="student-rank">{{ forloop.counter }}</td>
                              <td>{{ result.student.user.user.id }}</td>
                              <td><a target="_blank" href="{% url 'Student:profile' result.student.user.user.id %}" class="question-response-count student-name">{{ result.student.user.user.first_name }} {{ result.student.user.user.last_name }}</a></td>
                              <td class="marks-obtained">{{ result.marks_obtained }} / {{ conducted_quiz.quiz.max_marks }}</td>
                              <td>
                                {% if result.marks_obtained >= conducted_quiz.quiz.pass_marks %}Pass{% endif %}
                                {% if result.marks_obtained < conducted_quiz.quiz.pass_marks %}Fail{% endif %}
                              </td>
                            </tr>
                          {% endfor %}
                        </tbody>
                        {% endif %}
                        </table> -->
                  </div>
                </div>
            </div>
  </section>


{% endblock %}

{% block scripts %}
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
  
    <script>
      function filter_by_keyword(filter)
      {
        var cards = document.getElementById("rank-list");
        var c1 = cards.getElementsByClassName("rank-list-card");
        var count = 0;
        for( i = 0; i<c1.length; i++)
        {
            filter= filter.toUpperCase();

            var marks_obtained_div = c1[i].getElementsByClassName("marks-obtained");
            var marks_obtained = marks_obtained_div[0].innerHTML;

            var student_name_div = c1[i].getElementsByClassName("student-name");
            var student_name = student_name_div[0].innerHTML;

            var student_rank_div = c1[i].getElementsByClassName("student-rank");
            var student_rank = student_rank_div[0].innerHTML;

            if(marks_obtained.toUpperCase().indexOf(filter) > -1 || student_name.toUpperCase().indexOf(filter) > -1 || student_rank.toUpperCase().indexOf(filter) > -1)
                c1[i].style.display = '';
            else
                c1[i].style.display = 'none';
        }
      }
    </script>
{% endblock %}

WEBSITE-master/Professor/templates/Professor/verify_account.html
{% extends 'Professor/main.html' %}
{% load staticfiles %}

{% block title %}
    Verify account
{% endblock %}

{% block body %}
    {% include 'UserAuth/message.html' %}

    {{ request.user }}<br>
    verify account
    <br><br>

    Verify Email account<br>
        <a href="{% url 'UserAuth:send-verification-data' 'Professor' 'email' %}">Click Here...</a>
    <br><br>
    Verify Phone No.<br>
        <a href="{% url 'UserAuth:send-verification-data' 'Professor' 'mobile_no' %}">Click Here...</a>
    <br><br>
    <a href="{% url 'UserAuth:logout' %}">LOGOUT</a>
{% endblock %}

{% block scripts %}
    <script>
        function send_for_verification(send_to)
        {
            console.log(send_to);
        }
    </script>
{% endblock %}